### ISSUE TITLE
Readme link issue

### ISSUE THREAD

**Issue by zenntenn** [vossi1/c64-v9958-card#2]
In the README.md, there's near the top 

```
**www.mos6502.net**
```

That needs to be changed to 

```
**[www.mos6502.net](http://www.mos6502.net)**
```
as GitHub defaults the links to HTTPS, and that site is only HTTP.

**Comment by vossi1** [comment]
I changed the link to mos6509.com - this is my real site in https.
mos6502.net only refers to 6509.com.
But for me the 6502.net link works also in the readme - what browser did you used?

**Comment by zenntenn** [comment]
I used Chrome on Android
